# load("//scala:scala.bzl", "scala_library")
load(":test_discovery.bzl", "make_test_discovery")

make_test_discovery()

# scala_library(
#     name = "test_discovery",
#     srcs = [
#         "DiscoveredTestSuite.scala",
#         "FilteredRunnerBuilder.scala",
#     ],
#     visibility = ["//visibility:public"],
#     deps = ["@io_bazel_rules_scala//testing/toolchain:junit_classpath"],
# )
